app: usvisascheduler
service: visa-rescheduler-lambda

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  region: ${env:AWS_REGION, 'us-east-1'}
  logRetentionInDays: 5
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'iam:PassRole'
          Resource:
            - 'arn:aws:iam::${aws:accountId}:role/${self:service}-${self:provider.stage}-${aws:region}-lambdaRole'
        - Effect: Allow
          Action:
            - 'scheduler:GetSchedule'
            - 'scheduler:UpdateSchedule'
          Resource:
            - 'arn:aws:scheduler:${aws:region}:${aws:accountId}:schedule/default/${self:service}*'
  ecr:
    images:
      img:
        path: ./
        platform: linux/amd64

functions:
  main:
    timeout: 60
    memorySize: 2048
    image:
      name: img
    events:
      - schedule:
          method: scheduler
          rate: rate(${file(./json_var.json):retry_value, '10'} minutes)
